### ISSUE TITLE
can't install on YNH debian 8

### ISSUE THREAD

**Issue by bachy** [movim/movim_ynh#17]
Hello,

i tried yesterday to install movim app and it worked quite well.
Today, and a new YNH instance later (i crashed the precedent) i wanted to install movim again but it deosn't work anymore ...
```
$ yunohost app install https://github.com/movim/movim_ynh
Downloading...
Cloning into '/var/cache/yunohost/from_file'...
fatal: unable to access 'https://github.com/movim/movim_ynh/': Could not resolve host: github.com
Error: Invalid app manifest
```

**Comment by src386** [comment]
Weird... could you please check your DNS resolution ? Check resolv.conf and try this : 

    dig linuxfr.org

**Comment by bachy** [comment]
resolv.conf
```
nameserver 127.0.0.1
nameserver 213.186.33.99
search ovh.net
```
its's an ovh private server

gig linuxfr.org
```
; <<>> DiG 9.9.5-9+deb8u5-Debian <<>> linuxfr.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 39926
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;linuxfr.org.			IN	A

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Jan 27 21:14:45 CET 2016
;; MSG SIZE  rcvd: 29
```

**Comment by src386** [comment]
Okay, you do have a DNS problem. 
Looks like 127.0.0.1 is unable to solve anything.
It's a yunohost bug, you should remove the first line in your /etc/resolv.conf, just keep : 

    nameserver 213.186.33.99

**Comment by bachy** [comment]
src386 thank you !
i had to reboot but it's working now

**Comment by src386** [comment]
You are welcome
