### ISSUE TITLE
Git configure name, email

### ISSUE THREAD

**Issue by M5oul** [movim/movim_ynh#20]
You must configure name and email on the git of the instance where you commit/push.
[Tutorial](https://git-scm.com/book/fr/v1/Personnalisation-de-Git-Configuration-de-Git).
We could say, [I contribute more than you on this package](https://github.com/movim/movim_ynh/graphs/contributors) :smile_cat:
That way, your commits will be associated to your GitHub account.

I will let you close this issue.

**Comment by src386** [comment]
> You must configure name and email on the git of the instance where you commit/push.

Took me some time, but I fixed it, thank you.

> We could say, I contribute more than you on this package

THEY TOOK OUR JOBS ;)
