### ISSUE TITLE
Is port asking at install relevant?

### ISSUE THREAD

**Issue by M5oul** [movim/movim_ynh#22]
I don't think it good idea to ask internal port at install for non technical users.
It is relevant enough to ask it?

**Comment by src386** [comment]
It's because I am not sure that port is always available.
Non technical user should just leave default (9537), a check is performed.

**Comment by M5oul** [comment]
You could increment the port if it's used.
I have same issue with [ucoin_ynh](https://github.com/ucoin-io/ucoin_ynh/issues/6).
We should add a command on yunohost which test if the port is available, open it. If used, open an other.

**Comment by src386** [comment]
This idea is interesting, thanks.
I will try to implement this and see if it looks cool
