### ISSUE TITLE
Errors installation

### ISSUE THREAD

**Issue by tbille** [movim/movim_ynh#23]
Hi I am trying to install Movim on a Debian Jessie with a letsencrypt certificate.
The app is installed but I have a blank page when I try to go on it. I tried to reinstall it, and I saw this message (I just took the error messages) : 

        + sudo su -c 'cd /var/www/movim && php mud.php db set' movim
        <div style="font-family: Arial; text-align: center;">
            <h2>Oops... something went wrong.</h2>
            <p>But don't panic. The NSA is on the case.</p>
        </div>
        + sudo su -c 'cd /var/www/movim && php mud.php config locale:fr' movim
        <div style="font-family: Arial; text-align: center;">
            <h2>Oops... something went wrong.</h2>
            <p>But don't panic. The NSA is on the case.</p>
        </div>
        + sudo su -c 'cd /var/www/movim && php mud.php config loglevel:1' movim
        <div style="font-family: Arial; text-align: center;">
            <h2>Oops... something went wrong.</h2>
            <p>But don't panic. The NSA is on the case.</p>
        </div>
        + sudo su -c 'cd /var/www/movim && php mud.php config environment:production' movim
        <div style="font-family: Arial; text-align: center;">
            <h2>Oops... something went wrong.</h2>
            <p>But don't panic. The NSA is on the case.</p>
        </div>
        + sudo su -c 'cd /var/www/movim && php mud.php config timezone:Europe/Paris' movim
        <div style="font-family: Arial; text-align: center;">
            <h2>Oops... something went wrong.</h2>
            <p>But don't panic. The NSA is on the case.</p>
        </div>
        + sudo su -c 'cd /var/www/movim && php mud.php config username:user@domain.tld' movim
        <div style="font-family: Arial; text-align: center;">
            <h2>Oops... something went wrong.</h2>
            <p>But don't panic. The NSA is on the case.</p>
        </div>
        ++ awk '{print $1}'
        ++ sha1sum
        ++ echo -n 'monSuperPassword'
        + sudo su -c 'cd /var/www/movim && php mud.php config password:hash' movim
        <div style="font-family: Arial; text-align: center;">
            <h2>Oops... something went wrong.</h2>
            <p>But don't panic. The NSA is on the case.</p>
        </div>

**Comment by src386** [comment]
Hi, something went wrong earlier.
Maybe a missing dependancie (in php compozer) or a problem with database.
Can you delete then reinstall the package and paste the full output ?

**Comment by src386** [comment]
Ok, this should work now.
You can deinstall then reinstall, or just upgrade : 

    yunohost app upgrade movim -u https://github.com/movim/movim_ynh

**Comment by M5oul** [comment]
The screen is no more white.
The upper issue is still present.

**Comment by tbille** [comment]
The upgrade didn't work. But uninstall and install works!
Thanks

**Comment by src386** [comment]
Thanks for reporting this bug. Have fun with movim.

**Comment by M5oul** [comment]
Same for me.
