### ISSUE TITLE
group server list

### ISSUE THREAD

**Issue by bachy** [movim/movim_ynh#25]
Hi,
on pod.movim.eu i have a nice list of group servers in wich i can pick what i am interrested on.
but on my yunohost instance this list does not exists, i have to know a server to search on it.
Is it a bug ?

**Comment by src386** [comment]
Hi,
Sorry I don't understand, is it in the login page ?
Or after logged in, in the news feed ?

**Comment by src386** [comment]
Okay, I asked Edhelas, this is not a bug, the default list is empty.
On pod.movim.eu groups are shown because they have been added by the administrator but this is not the normal behavior.
On your pod, simply use the search field to discover groups (news.movim.eu for example).

**Comment by bachy** [comment]
ok, thank's for the info src386!
I think groups may be more intuitive for new comers with a list like in pod.movim.eu
Decentralization is the good way but it needs an "annuaire" to find other folks
