### ISSUE TITLE
Add a check for vendor/autoload.php before using mud.php

### ISSUE THREAD

**Issue by alexAubin** [movim/movim_ynh#27]
Hellow,

I would suggest adding a small check in the install script before using mud.php around lines 85-95, to check for the presence of `vendor/autoload.php`. I had an issue recently, trying to install movim on a server, and the composer step failed.

Cheers !

**Comment by src386** [comment]
Hi,
So your suggestion is to check if php composer steps are successful before going further.
Hm, why not, I will try to find something.
