### ISSUE TITLE
Can't join image when writting new actuallity

### ISSUE THREAD

**Issue by M5oul** [movim/movim_ynh#29]

**Comment by src386** [comment]
Works for me with this : 

    ![test](https://diaspora-fr.org/camo/4c15a2cc07577a0145a5800970e313caa0eb0857/68747470733a2f2f706f642e6f726b7a2e6e65742f75706c6f6164732f696d616765732f7363616c65645f66756c6c5f30653438363138396434353432343065333964372e676966)

Can you detail steps to reproduce please.

**Comment by opensc12** [comment]
I can't add image from my local files, the attachment button is hidden, I think it's the same problem.

**Comment by edhelas** [comment]
Does your server supports HTTP Upload? Movim will only enable it in this case.

**Comment by opensc12** [comment]
My server is a fresh install of Debian + Yunohost, and it use all params by default.
Owncloud upload works fine from my browser.
So there is something to add ?

**Comment by src386** [comment]
Looks like a feature request for Yunohost.

**Comment by tantic** [comment]
Hi,

I've got exactly the same issue, have you found the solution? I can upload an avatar but i don't have the attachment button to upload a file on the discussion screen. I tried to modify the movim.conf by adding the cors settings in the header but it didn't work. I also tried to add the directive client_max_body_size 

Thanks!!!

**Comment by src386** [comment]
Hello,
This is related to the Metronome implementation in Yunohost, so there is nothing we can do for now...

**Comment by tantic** [comment]
Ok thanks, should i open an issue in yunohost project or is it already in the roadmap?

**Comment by tantic** [comment]
Ok i found this https://dev.yunohost.org/issues/67 so it seems that there's a question about migrate from metronome to some other solution but with the problem of having the same functionalities and the migration of datas
