### ISSUE TITLE
New release: movim 0.10

### ISSUE THREAD

**Issue by maclag** [movim/movim_ynh#30]
Ils there a plan to have the 0.10 in yunohost?

**Comment by edhelas** [comment]
Already done :
https://github.com/movim/movim_ynh/commit/a2839c00ef51255260471cce78dc0b82f4f2426e

**Comment by edhelas** [comment]
Or do you mean as a stable release inside the Yunohost project ?

**Comment by src386** [comment]
Hi @maclag,
edhelas is right, the yunohost package has movim 0.10 already.
If you are unable to install it, please let me know.

**Comment by maclag** [comment]
Ok, my bad. The page on ynh site (app description) is still mentioning last update on 12th of february, I didn't check further.
I have issues with the upgrade, but I think I'll open a different ticket.

**Comment by src386** [comment]
Aw, I see. Indeed, I did not updated the revision in the list.
Please take a look at this : https://github.com/movim/movim_ynh

**Comment by maclag** [comment]
Thanks @src386, I did!
Well, I also broke my install with a stupid manipulation but that's me playing around while I'm still the only user. Issue with the install is fixed as well: it was getcomposer.org down (or very very slow responding), so fixed by itself.
I have now the 0.10 running, will test it thoroughly after work!
Thanks!
