### ISSUE TITLE
Backup/restore feature

### ISSUE THREAD

**Issue by JimboJoe** [movim/movim_ynh#31]
Could you please consider this functionality in the future?
Isthere any issue/hard point that prevent this feature from being implemented?

Thanks!

Note: This will be required if we want this YunoHost package to become an official one.

**Comment by src386** [comment]
Hello,
Well the reason why there is no backup/restore feature is because there is just nothing to backup.
All data are stored in Metronome (xmpp server).

**Comment by JimboJoe** [comment]
OK, that seems like a good reason :-)
But the backup would at least backup the parameters set during installation (domain, path, etc.), and help recover/move to another instance of YunoHost server?
I'm thinking of YunoHost backups as a quick way to set-up a new YunoHost server and restore my services, in case of hardware failure of my server.

**Comment by src386** [comment]
Why not, I'll tag this as a feature request :)
