### ISSUE TITLE
Cannot properly clean reinstall

### ISSUE THREAD

**Issue by jellium** [movim/movim_ynh#33]
I remove a Movim installation with the following:
`sudo yunohost app remove movim --debug --verbose`

I verify that the _movim_ SQL database is deleted, as well as _/var/www/movim_ and see that `locate movim` returns nothing.

I reinstall Movim with:
`sudo yunohost app install https://github.com/movim/movim_ynh --debug --verbose`

I clear my browser cache, log in on my "fresh" Movim install and see that all the previous posted data are still here.

Did I do anything wrong?

Thanks!

**Comment by matlag** [comment]
You did nothing wrong, but you wanted to wipe data, you shot the wrong target. The data are stored on the XMPP server, Movim is just a (very good) client. Movim stores a cache, but data are supposed to be available from any other client as well.

**Comment by jellium** [comment]
OK, got it. Thanks! Perhaps the script that handles removal from YunoHost should update the metronome xmpp data base accordingly.

**Comment by JimboJoe** [comment]
Movim is only an XMPP client: YunoHost provides the XMPP server and stores the data.
In my opinion, removing the client shouldn't wipe the data on the server.
I propose to close this issue.

**Comment by matlag** [comment]
I would strongly oppose the idea of deleting anything on the server when removing the client!
One should be able to remove a client, install another one and find back all data.
With the same logic, would you wipe out IMAP emails and contacts when you remove an email client?
