### ISSUE TITLE
Can't login - no clear error message

### ISSUE THREAD

**Issue by arthurlutz** [movim/movim_ynh#34]
I'm not sure this is issue #21 

I'm using movim on another domain as my main yuno domain so yuno is on example.org and movim is on jabber.example.org

I try to login and there is no clear error. I get a "Accounts" page with the account I tried to login with (and a administration button and "another account" button).

Looking at network inspect in the browser I see that the websocket is in station "101 switching protocols" is that normal ? On the frames tab I do see the frames asking for registration, but then I get redirected to ?disconnect... 

I've tried to add in "Adresses supplémentaires" arthur@jabber.example.org in the accounts... doesn't seem to change anything.

**Comment by src386** [comment]
Is it a working jid ? Can you use it with another client (such as Pidgin, Gajim...) ?

**Comment by src386** [comment]
Try this : 

1) Open jabber.example.org/movim/?admin (assuming your pod is jabber.example.org/movim)

2) Use the user / password you definied during Movim installation.

3) Go to the tab "GENERAL SETTINGS"

4) In the **Whitelisted XMPP Servers** section, add your jid domain (example.org)
