### ISSUE TITLE
Missing YunoHost tile

### ISSUE THREAD

**Issue by JimboJoe** [movim/movim_ynh#36]
Add the required block to nginx configuration file:
```
# Include SSOWAT user panel.
include conf.d/yunohost_panel.conf.inc;
```
In case you fear it will make the app unusable because the tile button is on top of the send button by default, don't forget you can drag&drop it ;-)

Note: This will be required if we want this YunoHost package to become an official one.

**Comment by src386** [comment]
I need to check it out, there's probably a reason why I commented the code in the vhost.

https://github.com/movim/movim_ynh/blob/master/conf/nginx.conf#L61

**Comment by src386** [comment]
Done
