### ISSUE TITLE
Creating a new movim account

### ISSUE THREAD

**Issue by sidiousdk** [movim/movim_ynh#37]
hi,
I installed movim on Yunohost.

It works great with accounts on the SSO.
I allowed registration on my jabber server (metronome), and add it in whitelist of movim configuration (just in case).

When I try to register, nothing (at all) happen when I clic on "register" button.

When I try to register with an account already in the SSO it tell me "the requested username already exists"

Is it a user (me) issue or something doesn't work between movim and yunohost ?

thanks :)

**Comment by src386** [comment]
In Yunohost, Metronome uses ldap authentication.
It is not recommended to create new xmpp accounts, I don't even know if it's possible. You are supposed to use yunohost admin.
