### ISSUE TITLE
Movim 0.13

### ISSUE THREAD

**Issue by matlag** [movim/movim_ynh#40]
Hi!

So, 0.13 is out, and as usual, I volunteer for testing it out!

Thanks and Merry Christmas!

**Comment by src386** [comment]
Hi,
Movim 0.13 has a composer dependence (evenement) that requires php7.0.
I'm runnnig Yunohost on Debian Jessie (php5.6) so I cannot install Movim 0.13.

**Comment by src386** [comment]
Added a note to https://github.com/movim/movim/issues/543

**Comment by src386** [comment]
Solved, Movim 0.13 lives
https://github.com/movim/movim_ynh/commit/a4c309081bd8eedfc7f1865b91b416e83689a79f
